name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'TEST_PYPI'
        type: choice
        options:
        - 'PYPI'
        - 'TEST_PYPI'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Test package
      run: |
        apt install netcdf
        python3 -m pip install -e .
        python3 test_python_file.py

  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install build

    - name: Build package
      run: |
        python3 -m build

    - name: Publish to PyPI
      if: ${{ github.event.inputs.repository == 'PYPI' || github.event.inputs.repository == '' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish to test PyPI
      if: ${{ github.event.inputs.repository == 'TEST_PYPI' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
